project_id = "qxnwoyhjarjjbqyvytrb"

[functions.generate-text-lesson]
verify_jwt = false

[functions.generate-code]
verify_jwt = false

[functions.generate-audio-lesson]
verify_jwt = false

[functions.generate-visual]
verify_jwt = false